import { useState } from 'react'
import { motion } from 'framer-motion'
import {
  Brain, Zap, Droplets, AlertTriangle, DollarSign, Users,
  TrendingUp, TrendingDown, Info, Star, ChevronRight, Activity
} from 'lucide-react'
import { aiInsights } from '../data/aiInsights'
import { Card, CardContent, CardHeader, CardTitle } from '../components/ui/Card'
import {
  LineChart, Line, BarChart, Bar, AreaChart, Area,
  XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, ReferenceLine
} from 'recharts'
import { cn } from '../utils/cn'

const iconMap = { AlertTriangle, DollarSign, Zap, Droplets, Users }

const chartTypeMap = {
  'ai-01': 'bar',
  'ai-02': 'area',
  'ai-03': 'line',
  'ai-04': 'line',
  'ai-05': 'bar',
}

export default function AIInsightsPage() {
  const [activeCard, setActiveCard] = useState(null)

  return (
    <motion.div initial={{ opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }} className="space-y-6">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <div className="flex items-center gap-2 mb-1">
            <div className="w-8 h-8 rounded-xl bg-gradient-to-br from-purple-600 to-primary-600 flex items-center justify-center">
              <Brain size={18} className="text-white" />
            </div>
            <h1 className="text-2xl font-bold text-gray-900 dark:text-gray-100 font-display">AI Insights</h1>
          </div>
          <p className="text-sm text-gray-500 dark:text-gray-400">
            Powered by machine learning models trained on historical society data
          </p>
        </div>
        <div className="flex items-center gap-2 px-4 py-2 bg-purple-50 dark:bg-purple-900/20 rounded-xl border border-purple-200 dark:border-purple-800">
          <Activity size={14} className="text-purple-600" />
          <span className="text-xs font-semibold text-purple-700 dark:text-purple-400">All Models Active</span>
          <div className="w-2 h-2 rounded-full bg-purple-500 animate-pulse ml-1" />
        </div>
      </div>

      {/* Disclaimer */}
      <div className="flex items-start gap-3 p-4 bg-blue-50 dark:bg-blue-900/20 rounded-2xl border border-blue-200 dark:border-blue-800">
        <Info size={16} className="text-blue-600 dark:text-blue-400 flex-shrink-0 mt-0.5" />
        <p className="text-xs text-blue-700 dark:text-blue-300 leading-relaxed">
          These predictions are generated by ML models and are for informational purposes only.
          Confidence scores represent model accuracy on historical validation data.
          Always use human judgment for critical decisions.
        </p>
      </div>

      {/* Insight Cards */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {aiInsights.map((insight) => {
          const Icon = iconMap[insight.icon] || Brain
          const chartType = chartTypeMap[insight.id] || 'line'
          const isExpanded = activeCard === insight.id

          return (
            <motion.div
              key={insight.id}
              layout
              className={cn(
                'bg-white dark:bg-gray-800 rounded-2xl border border-gray-100 dark:border-gray-700/50 shadow-card overflow-hidden',
                insight.id === 'ai-04' && insight.alert ? 'ring-2 ring-amber-400 dark:ring-amber-600' : '',
                isExpanded && 'lg:col-span-2'
              )}
            >
              {/* Card Header Gradient */}
              <div className={cn('p-5 bg-gradient-to-br', insight.bgColor)}>
                <div className="flex items-start justify-between mb-4">
                  <div className="flex items-center gap-3">
                    <div className="w-10 h-10 rounded-2xl bg-white/50 dark:bg-gray-900/30 flex items-center justify-center">
                      <Icon size={20} style={{ color: insight.color }} />
                    </div>
                    <div>
                      <h3 className="text-sm font-bold text-gray-900 dark:text-gray-100">{insight.title}</h3>
                      <p className="text-xs text-gray-500 dark:text-gray-400">{insight.subtitle}</p>
                    </div>
                  </div>
                  {/* Confidence Score */}
                  <div className="text-right">
                    <div className="flex items-center gap-1">
                      <Star size={12} className="text-yellow-500 fill-yellow-500" />
                      <span className="text-lg font-bold text-gray-900 dark:text-gray-100">{insight.confidence}%</span>
                    </div>
                    <p className="text-xs text-gray-400">Confidence</p>
                  </div>
                </div>

                {/* Alert */}
                {insight.alert && (
                  <div className={cn('flex items-center gap-2 p-2.5 rounded-xl mb-3 text-xs font-medium',
                    insight.alert.type === 'warning' ? 'bg-amber-100 dark:bg-amber-900/40 text-amber-700 dark:text-amber-400' : 'bg-red-100 dark:bg-red-900/40 text-red-700 dark:text-red-400'
                  )}>
                    <AlertTriangle size={13} />
                    {insight.alert.message}
                  </div>
                )}

                {/* Prediction Text */}
                <div className="p-3 bg-white/50 dark:bg-gray-900/30 rounded-xl mb-3">
                  <p className="text-sm font-semibold text-gray-900 dark:text-gray-100">{insight.prediction}</p>
                  <p className="text-xs text-gray-500 dark:text-gray-400 mt-1">{insight.details}</p>
                </div>

                {/* Mini Chart */}
                <ResponsiveContainer width="100%" height={100}>
                  {chartType === 'bar' ? (
                    <BarChart data={insight.chartData} barSize={10}>
                      <XAxis dataKey={Object.keys(insight.chartData[0])[0]} tick={{ fontSize: 9 }} />
                      <YAxis hide />
                      <Tooltip contentStyle={{ fontSize: 11, borderRadius: 8 }} />
                      <Bar dataKey="actual" name="Actual" fill={insight.color} radius={[3,3,0,0]} opacity={0.8} />
                      <Bar dataKey="predicted" name="Predicted" fill={insight.color} radius={[3,3,0,0]} opacity={0.4} />
                    </BarChart>
                  ) : (
                    <LineChart data={insight.chartData}>
                      <XAxis dataKey={Object.keys(insight.chartData[0])[0]} tick={{ fontSize: 9 }} />
                      <YAxis hide />
                      <Tooltip contentStyle={{ fontSize: 11, borderRadius: 8 }} />
                      {insight.chartData[0]?.baseline && (
                        <ReferenceLine y={insight.chartData[0].baseline} stroke="#6b7280" strokeDasharray="4 4" />
                      )}
                      <Line type="monotone" dataKey="usage" name="Usage" stroke={insight.color} strokeWidth={2} dot={false} />
                      <Line type="monotone" dataKey="forecast" name="Forecast" stroke={insight.color} strokeWidth={2} strokeDasharray="5 5" dot={false} opacity={0.6} />
                    </LineChart>
                  )}
                </ResponsiveContainer>
              </div>

              {/* Insights & Recommendations */}
              <div className="p-5">
                <div className={cn('grid gap-4', isExpanded ? 'grid-cols-2' : 'grid-cols-1')}>
                  <div>
                    <p className="text-xs font-semibold text-gray-500 dark:text-gray-400 uppercase tracking-wider mb-2">Key Insights</p>
                    <ul className="space-y-1.5">
                      {insight.insights.slice(0, isExpanded ? 4 : 3).map((ins, i) => (
                        <li key={i} className="flex items-start gap-2 text-xs text-gray-600 dark:text-gray-400">
                          <span className="w-1.5 h-1.5 rounded-full mt-1.5 flex-shrink-0" style={{ background: insight.color }} />
                          {ins}
                        </li>
                      ))}
                    </ul>
                  </div>
                  {isExpanded && (
                    <div>
                      <p className="text-xs font-semibold text-gray-500 dark:text-gray-400 uppercase tracking-wider mb-2">Recommendations</p>
                      <ul className="space-y-1.5">
                        {insight.recommendations.map((rec, i) => (
                          <li key={i} className="flex items-start gap-2 text-xs text-gray-600 dark:text-gray-400">
                            <ChevronRight size={12} className="mt-0.5 flex-shrink-0 text-green-500" />
                            {rec}
                          </li>
                        ))}
                      </ul>
                    </div>
                  )}
                </div>

                <div className="mt-4 flex items-center justify-between">
                  <div className="flex items-center gap-4 text-xs text-gray-400">
                    <span>Model: {insight.model}</span>
                    <span>Updated: {insight.lastUpdated}</span>
                  </div>
                  <button
                    onClick={() => setActiveCard(isExpanded ? null : insight.id)}
                    className="text-xs text-primary-600 dark:text-primary-400 font-medium hover:underline flex items-center gap-1"
                  >
                    {isExpanded ? 'Collapse' : 'See Recommendations'} <ChevronRight size={12} />
                  </button>
                </div>
              </div>
            </motion.div>
          )
        })}
      </div>

      {/* Model Performance Footer */}
      <Card>
        <CardContent>
          <div className="flex flex-col sm:flex-row items-center justify-between gap-4">
            <div>
              <p className="text-sm font-semibold text-gray-900 dark:text-gray-100">AI Infrastructure Status</p>
              <p className="text-xs text-gray-400 mt-1">Models retrain nightly on latest society data</p>
            </div>
            <div className="flex flex-wrap gap-6">
              {aiInsights.map(ins => (
                <div key={ins.id} className="text-center">
                  <div className="flex items-center justify-center gap-1 mb-1">
                    <div className="w-2 h-2 rounded-full bg-green-500 animate-pulse" />
                    <span className="text-xs text-gray-400">{ins.title.split(' ').slice(0,2).join(' ')}</span>
                  </div>
                  <p className="text-sm font-bold text-gray-900 dark:text-gray-100">{ins.confidence}%</p>
                </div>
              ))}
            </div>
          </div>
        </CardContent>
      </Card>
    </motion.div>
  )
}
